### ISSUE TITLE
lanages % are wronge

### ISSUE THREAD

**Issue by micfun123** [omsimos/github-stats-generator#6]
According to your site, C is my most used language. I can guarantee with public repos and private repos its far from the amount of python I have written.  you may want to look in to the accuracy of your site

**Comment by joshxfi** [comment]
hello @micfun123, our website only displays the result from the APIs which makes it easier to view different themes.

the data generated on your stats are handled by:
[anuraghazra/github-readme-stats](https://github.com/anuraghazra/github-readme-stats)
[DenverCoder1/github-readme-streak-stats](https://github.com/DenverCoder1/github-readme-streak-stats)

you may raise an issue on their repos if you believe that the stats generated are inaccurate. cheers!

**Comment by micfun123** [comment]
Ah ok thank you
